# Generated by Django 5.2.8 on 2025-11-28 09:02

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactpage_servicespage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Contenu principal : histoire, mission, valeurs...', verbose_name='Texte de présentation'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image_caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Légende de l’image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='intro_subtitle',
            field=models.TextField(blank=True, default='En savoir plus sur nous.', help_text='Une petite phrase pour introduire la page.', verbose_name='Texte d’intro'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_address',
            field=models.CharField(blank=True, default='Adresse de votre entreprise', max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_email',
            field=models.EmailField(blank=True, default='contact@exemple.com', max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_text',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Ex : "Utilisez ce formulaire comme base..."', verbose_name='Texte au-dessus du formulaire'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro_subtitle',
            field=models.TextField(blank=True, default='Un exemple de page contact avec un formulaire simple.', help_text="Ex : 'Un exemple de page contact avec un formulaire simple.'", verbose_name='Texte d’intro'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_kicker',
            field=models.CharField(blank=True, default='Bienvenue', help_text="Ex : 'Agence digitale · Exemple Wagtail'", max_length=150, verbose_name='Petit texte au-dessus du titre'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Sous-titre de présentation pour la page d’accueil.', help_text='Quelques phrases qui expliquent le site.', verbose_name='Texte sous le titre'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Titre de la page d’accueil', help_text="Ex : 'Créez un site vitrine moderne, clair et efficace.'", max_length=200, verbose_name='Titre principal'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_preview_intro',
            field=models.TextField(blank=True, default='Un aperçu rapide de nos services.', help_text='Petite phrase pour introduire les services.', verbose_name='Texte d’intro de la section services (accueil)'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='intro_subtitle',
            field=models.TextField(blank=True, default='Voici un exemple de section services que vous pouvez adapter.', help_text="Ex : 'Voici un exemple de section services...'", verbose_name='Texte d’intro'),
        ),
    ]
