# Generated by Django 5.2.8 on 2025-12-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactpage_formationspage_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_association', models.CharField(default='Femmes Solidaires', max_length=100, verbose_name="Nom de l'association")),
                ('slogan', models.CharField(default='Formation · Emploi · Solidarité', max_length=100, verbose_name='Slogan')),
                ('description', models.TextField(default='Association locale engagée pour l’émancipation des femmes par la formation et l’emploi. Ensemble, construisons votre avenir.', verbose_name='Texte de présentation')),
                ('annee', models.CharField(default='2025', max_length=4, verbose_name='Année affichée en bas')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Logo de l'association")),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
